{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}
{% set cran_mirror = 'https://cran.r-project.org' %}

package:
  name: r-htree
  version: {{ version|replace("-", "_") }}

source:
  fn: htree_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/htree_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/htree/htree_{{ version }}.tar.gz
  sha256: 8b3709dc0ead4ac46859a660a5174c5dc843083a5a84392e8cf02972052b7195

build:
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('htree')"           # [not win]
    - "\"%R%\" -e \"library('htree')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=htree
  license: GPL (>= 2)
  summary: Historical regression trees are an extension of standard trees,  producing a non-parametric
    estimate of how the response depends on  all of its prior realizations as well as
    that of any time-varying predictor  variables. The method applies equally to regularly
    as well as irregularly  sampled data. The package implements random forest and boosting
    ensembles  based on historical regression trees, suitable for longitudinal data.  Standard
    error estimation and Z-score variable importance is also implemented.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
