travis:
  secure:
    BINSTAR_TOKEN: QcCU9hVUnggdYnfA5ufx1VZ4Hn4IJP16I+alSx10sslG2ArpPolRrz2MDD2bwQJeMVgKizaa9m8AuVKAWiukoSBWzcTrny7tqyI59syPXuK9UUFxzFq9V9YKkYYIo0JkU80btxBh86jtRInD45xRg1DBCuBsrrtW0ADevaWISpBbj/TSjlguUJ+nEN6Z6wXY2P2uAlBSnxfv3Yh+hwNGU5wPHfkZQro6sR9j+XLsZDLmlS25WIjXPNKOU35QfEaGnSBG7PNWIIKurer7H1ZxzN8sNdBJy6RePzLNtNKr4DuQRoa3nSxQ/leezWCrygUeZo4pbRVJZrkkI+48PTC5xDtDEuCJZ0U5FgF3VwYN+cLeFUT7o12x0hiMD+TJKqwoDneDOkCmUDj3H7f+esZbfiQ/8KK4y7PIAnIyrKe0wCWOnzdMK/k9Ufs19YB5tofuP6ilwVv1EWrxIc86Tyh0sPo/Siq4MjcgPRLE8V/1747GzPB5/OiJcBGmquHC2tEFHZEJ3OfS0DWCJqYP+KHlZlkVRknSJ850wj7zKDTKBX/BygUqH+rth2ZE1s4Ktdxl0TGUUZTCx8aN7gRy+9KfDRVGG9cMWmCsmETGAn0uPAUDjPICCCxgPsrHn78mN0ic5nF8NOypiHDU8/N8zpF5Z/PLDZXoc3Hacx4etGpd2rk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
