appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: YDcXMRK5py7GpEnZ8AwEO4B45V/pA+ibISbMtRkzHhYpMturymv5WqQnWogBr28UxmlAJ30TU5F79wgqKuCQJe3k/b6B63z5GuwCISlIxdFnJSQ0aZWAyCmiSUbrhNP0K4pPcxMTxekWajwsT2uPLOj8fG47IDuzL1XEnwrM9t1X9Oam+fJPFC/QIQ++/Rkm3gy5O7Qb2JYNZy2WHiX6FdSKD/5ZohyLGc05HxjMoL+F5vsuyjdd6lOVvmNfc03kBKtZbadjY66cwbKwQQ3Iu04PRgT46mFdOJPnZ9YXkDIBqLv9Mt15hYmwr8oc5dSaBlYFeztTHHiAeICsmuy0mpf72W7zUTzWOR7hS7xhpPnH2iW/9yzgmRDUP6p+QFM4R+B7RXPC1/7I0MoosFS0PUr9Tge0QySfujpwYgDcUmTGChM0yBUXJYVH95UZBRS0TsvccXPORUhBnY3uiECS9lyMRLcxU/6TsTaTjTtn1vLYduRs6wreKXoW/m/969PoOL4gvlUHEmzusbp8Q3h8tew2vAv3crGeJ1RrQ0YKzfpaRE69FgCXwfq/lnDly8o4+UhTRPtLa6uABfCNKs8tR5BpN8F+TOd62bRXrog+jDSvJLIptFHAZA1lyG6BvttkYCdpXhkx+Bx+azXTMVV9hj4dALpMmz5OTuKUxJU7vsw=}
